# Generated by Django 5.1.7 on 2025-03-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contactus_email_alter_contactus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(default='>>> Unknown@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
