# Generated by Django 5.1.7 on 2025-03-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_contactus_email_alter_contactus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='slider_news/')),
                ('slider_title', models.CharField(max_length=100)),
                ('slider_category', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
