# Generated by Django 5.1.7 on 2025-03-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_slider_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider_news',
            name='slider_content',
            field=models.TextField(default='Default content'),
        ),
    ]
