# Generated by Django 5.1.7 on 2025-03-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_slider_news_slider_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='small_slider_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_slider_image', models.ImageField(upload_to='small_slider_news/')),
                ('small_slider_title', models.CharField(max_length=100)),
                ('small_slider_content', models.TextField(default='Default content')),
                ('small_slider_category', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
