# Generated by Django 5.1.7 on 2025-03-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_small_slider_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider_news',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='small_slider_news',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
