# Generated by Django 5.1.7 on 2025-03-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_slider_news_is_activate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='small_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='small_slider_news/')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='Default content')),
                ('category', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='small_slider_news',
        ),
    ]
