# Generated by Django 5.1.7 on 2025-03-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_featurednews_delete_newsslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurednews',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
