# Generated by Django 5.1.7 on 2025-03-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('biznes', 'Biznes'), ('idman', 'Idman'), ('texnologiya', 'Texnologiya'), ('əyləncə', 'Əyləncə')], max_length=20)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
