# Generated by Django 5.1.7 on 2025-03-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('biznes', 'Biznes'), ('idman', 'Idman'), ('texnologiya', 'Texnologiya'), ('əyləncə', 'Əyləncə'), ('həyat tərzi', 'Həyat tərzi'), ('qida', 'Qida'), ('elmlər', 'Elmlər'), ('təhsil', 'Təhsil'), ('sağlamlıq', 'Sağlamlıq'), ('korporativ', 'Korporativ'), ('siyasət', 'Siyasət')], max_length=20),
        ),
    ]
