# Generated by Django 5.1.7 on 2025-03-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_trendingnews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrendingNews',
        ),
    ]
