# Generated by Django 5.1.7 on 2025-03-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_popularnews_content_alter_featurednews_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('biznes', 'Biznes'), ('idman', 'Idman'), ('texnologiya', 'Texnologiya'), ('əyləncə', 'Əyləncə'), ('həyat tərzi', 'Həyat tərzi'), ('qida', 'Qida'), ('elmlər', 'Elmlər'), ('təhsil', 'Təhsil'), ('sağlamlıq', 'Sağlamlıq'), ('korporativ', 'Korporativ'), ('siyasət', 'Siyasət'), ('din', 'Din'), ('cəmiyyət', 'Cəmiyyət')], max_length=20),
        ),
        migrations.AlterField(
            model_name='popularnews',
            name='category',
            field=models.CharField(choices=[('biznes', 'Biznes'), ('idman', 'Idman'), ('texnologiya', 'Texnologiya'), ('əyləncə', 'Əyləncə'), ('həyat tərzi', 'Həyat tərzi'), ('qida', 'Qida'), ('elmlər', 'Elmlər'), ('təhsil', 'Təhsil'), ('sağlamlıq', 'Sağlamlıq'), ('korporativ', 'Korporativ'), ('siyasət', 'Siyasət'), ('din', 'Din'), ('cəmiyyət', 'Cəmiyyət')], max_length=20),
        ),
    ]
