# Generated by Django 5.1.7 on 2025-03-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_news_category_alter_popularnews_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('biznes', 'Biznes'), ('idman', 'Idman'), ('texnologiya', 'Texnologiya'), ('əyləncə', 'Əyləncə'), ('həyat tərzi', 'Həyat tərzi'), ('qida', 'Qida'), ('elmlər', 'Elmlər'), ('təhsil', 'Təhsil'), ('sağlamlıq', 'Sağlamlıq'), ('korporativ', 'Korporativ'), ('siyasət', 'Siyasət'), ('din', 'Din'), ('cəmiyyət', 'Cəmiyyət')], max_length=20)),
                ('image', models.ImageField(upload_to='CategoryNews_images/')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
            ],
        ),
    ]
