# Generated by Django 5.1.7 on 2025-03-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_singlenews_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlenews',
            name='author',
            field=models.CharField(default='BizNews', max_length=100),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
